name: Test WiFi AP
version: dev
slug: test
description: WiFi AP based on RaspAP
url: https://github.com/rmariuso/hassio-addons/tree/main/ap_test
startup: system
advanced: true
panel_icon: mdi:router-wireless
panel_title: wifi AP
arch:
  - aarch64
  - amd64
  - armv7
map: 
  - config:rw
ingress: true
init: false
boot: manual
host_network: true
apparmor: true
#full_access: true
#host_dbus: true
udev: true
privileged:
  - SYS_ADMIN
  - NET_ADMIN
#ports:
#  8081/tcp: 8081
