name: Home Assistant WiFi AP_test
version: dev
slug: wifiap_ha 
description: WiFi AP based on RaspAP
url: https://github.com/rmariuso/hassio-addons/tree/main/WiFiAP_HA
startup: services
panel_icon: mdi:router-wireless
panel_title: WiFiAP_HA
arch:
  - aarch64
  - amd64
  - armv7
map: 
  - config:rw
ingress: true
#advanced: true
init: false
boot: manual
hassio_api: true
homeassistant_api: true
host_network: true
privileged:
#  - SYS_ADMIN
  - NET_ADMIN
options:
  client_internet_access: false
  language: English
schema:
  client_internet_access: bool
  language: list(English|Deutsch|Español|Français|Italiano|Română)