name: Home Assistant WiFi AP_test
version: dev
slug: wifiap_ha 
description: Create a WiFi AP based on raspap-webgui
url: https://github.com/rmariuso/hassio-addons/tree/main/WiFiAP_HA
#startup: services
panel_icon: mdi:router-wireless
arch:
  - aarch64
  - amd64
  - armv7
#map: 
#  - addon_config:rw
#ingress: true
#advanced: true
init: false
boot: auto
hassio_api: true
homeassistant_api: true
host_network: true
privileged:
#  - SYS_ADMIN
  - NET_ADMIN
options:
  client_internet_access: true
  language: English
schema:
  client_internet_access: bool
  language: list(English|Deutsch|Español|Français|Italiano|Română)