name: Home Assistant WiFi AP
version: dev
slug: wifiap
description: WiFi AP based on RaspAP
#url: https://github.com/rmariuso/hassio-addons/tree/main/WiFi_AP
startup: system
panel_icon: mdi:router-wireless
panel_title: wifi AP
arch:
  - aarch64
  - amd64
  - armv7
map: 
  - config:rw
ingress: true
init: false
boot: manual
host_network: true
#udev: true
apparmor: true
host_dbus: true
privileged:
  - SYS_ADMIN
  - NET_ADMIN
options:
  ssid:
  wpa_passphrase:
  channel: 6
  address: 192.168.99.1
  netmask: 255.255.255.0
  broadcast: 192.168.99.255
  interface: wlan0
  hide_ssid: false
  dhcp: false
  dhcp_start_addr: 192.168.99.10
  dhcp_end_addr: 192.168.99.20
  allow_mac_addresses: []
  deny_mac_addresses: []
  debug: 0
  hostapd_config_override: []
  client_internet_access: false
  client_dns_override: []
  dnsmasq_config_override: []
schema:
  ssid: match(^.{2,32}$)
  wpa_passphrase: password
  channel: int(1,13)
  address: match(^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$)
  netmask: match(^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$)
  broadcast: match(^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$)
  interface: str
  hide_ssid: bool
  dhcp: bool
  dhcp_start_addr: match(^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$)
  dhcp_end_addr: match(^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$)
  allow_mac_addresses:
    - match(^([0-9a-fA-F]{2}:){4}[0-9a-fA-F]{2})?
  deny_mac_addresses:
    - match(^([0-9a-fA-F]{2}:){4}[0-9a-fA-F]{2})?
  debug: int(0,2)
  hostapd_config_override:
    - str?
  client_internet_access: bool
  client_dns_override:
    - match(^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$)
  dnsmasq_config_override:
    - str?

#  client_internet_access: true
#  language: English
#schema:
#  client_internet_access: bool
#  language: list(English|Deutsch|Español|Français|Italiano|Română)