name: Home Assistant WiFi AP
version: dev
slug: wifiap
description: WiFi AP based on RaspAP
url: https://github.com/rmariuso/hassio-addons/tree/main/wifiap
startup: system
panel_icon: mdi:router-wireless
panel_title: WiFi AP
arch:
  - aarch64
  - amd64
  - armv7
map: 
  - config:rw
ingress: true
init: false
boot: manual
host_network: true
udev: true
privileged:
  - SYS_ADMIN
  - NET_ADMIN
options:
  interface_wlan: wlan0
schema:
  interface_wlan: str
