name: Home Assistant WiFi AP
version: dev
slug: wifiap_test
description: WiFi AP based on RaspAP
url: https://github.com/rmariuso/hassio-addons/tree/main/wifiap
startup: system
panel_icon: mdi:router-wireless
panel_title: wifi AP
arch:
  - aarch64
  - amd64
  - armv7
map: 
  - config:rw
#ingress: true
init: false
boot: manual
host_network: true
#udev: true
#apparmor: true
tmpfs: true
#host_dbus: true
privileged:
  - SYS_ADMIN
  - NET_ADMIN
ports:
  8081/tcp: 8081
options:
  RASPAP_SSID: raspap-webgui
  RASPAP_SSID_PASS: ChangeMe
  RASPAP_COUNTRY: GB
  RASPAP_WEBGUI_USER: admin
  RASPAP_WEBGUI_PASS: secret
  RASPAP_WEBGUI_PORT: 80
schema:
  RASPAP_SSID: str
  RASPAP_SSID_PASS: password
  RASPAP_COUNTRY: str
  RASPAP_WEBGUI_USER: str
  RASPAP_WEBGUI_PASS: password
  RASPAP_WEBGUI_PORT: int
